AspPoistenieBK02/AspPoistenieBK02/Controllers/InsuranceModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspPoistenieBK02.Data;
using AspPoistenieBK02.Models;

namespace AspPoistenieBK02.Controllers
{
    public class InsuranceModelsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InsuranceModelsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: InsuranceModels
        public async Task<IActionResult> Index()
        {
                
              return View(await _context.InsuranceModel.ToListAsync());
        }

        // GET: InsuranceModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.InsuranceModel == null)
            {
                return NotFound();
            }

            var insuranceModel = await _context.InsuranceModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (insuranceModel == null)
            {
                return NotFound();
            }

            return View(insuranceModel);
        }

        // GET: InsuranceModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: InsuranceModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,InsuranceType,Amount,Subject,ValidFrom,ValidTo")] InsuranceModel insuranceModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(insuranceModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
#warning po pridani redirect na details actual user

            return View(insuranceModel);
        }

        // GET: InsuranceModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.InsuranceModel == null)
            {
                return NotFound();
            }

            var insuranceModel = await _context.InsuranceModel.FindAsync(id);
            if (insuranceModel == null)
            {
                return NotFound();
            }
            return View(insuranceModel);
        }

        // POST: InsuranceModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,InsuranceType,Amount,Subject,ValidFrom,ValidTo")] InsuranceModel insuranceModel)
        {
            if (id != insuranceModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(insuranceModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InsuranceModelExists(insuranceModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(insuranceModel);
        }

        // GET: InsuranceModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.InsuranceModel == null)
            {
                return NotFound();
            }

            var insuranceModel = await _context.InsuranceModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (insuranceModel == null)
            {
                return NotFound();
            }

            return View(insuranceModel);
        }

        // POST: InsuranceModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.InsuranceModel == null)
            {
                return Problem("Entity set 'ApplicationDbContext.InsuranceModel'  is null.");
            }
            var insuranceModel = await _context.InsuranceModel.FindAsync(id);
            if (insuranceModel != null)
            {
                _context.InsuranceModel.Remove(insuranceModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InsuranceModelExists(int id)
        {
          return _context.InsuranceModel.Any(e => e.Id == id);
        }
    }
}

AspPoistenieBK02/AspPoistenieBK02/Controllers/UserModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspPoistenieBK02.Data;
using AspPoistenieBK02.Models;

namespace AspPoistenieBK02.Controllers
{
    public class UserModelsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserModelsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: UserModels
        public async Task<IActionResult> Index()
        {
              return View(await _context.UserModel.ToListAsync());
        }

        // GET: UserModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UserModel == null)
            {
                return NotFound();
            }

            var userModel = await _context.UserModel.FirstOrDefaultAsync(m => m.Id == id);
            if (userModel == null)
            {
                return NotFound();
            }

            if(userModel != null)
            {
                //ViewBag.UserInsuranceList = userModel.GetUserInsurances(_context, userModel.Id);
                userModel.SetUserInsurances(_context, userModel.Id);

                /*
                foreach(object o in userInsuranceList)
                    Console.WriteLine(o);
                */
            }

            return View(userModel);
        }

        // GET: UserModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Email,PhoneNumber,BirthDate,UserAdress,UserCity,UserZipCode,UserGender")] UserModel userModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userModel);
                await _context.SaveChangesAsync();
                TempData["CreateMsg"] = string.Format("Uzivatel {0} bol uspesne pridany!", userModel.ToString());
                return RedirectToAction(nameof(Index));
            }
            return View(userModel);
        }

        // GET: UserModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UserModel == null)
            {
                return NotFound();
            }

            var userModel = await _context.UserModel.FindAsync(id);
            if (userModel == null)
            {
                return NotFound();
            }
            return View(userModel);
        }

        // POST: UserModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Email,PhoneNumber,BirthDate,UserAdress,UserCity,UserZipCode,UserGender")] UserModel userModel)
        {
            if (id != userModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserModelExists(userModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["EditMsg"] = string.Format("Uzivatel {0} bol uspesne upraveny!", userModel.ToString());
                return RedirectToAction(nameof(Index));
            }
            return View(userModel);
        }

        // GET: UserModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UserModel == null)
            {
                return NotFound();
            }

            var userModel = await _context.UserModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userModel == null)
            {
                return NotFound();
            }

            return View(userModel);
        }

        // POST: UserModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UserModel == null)
            {
                return Problem("Entity set 'ApplicationDbContext.UserModel'  is null.");
            }
            var userModel = await _context.UserModel.FindAsync(id);
            if (userModel != null)
            {
                _context.UserModel.Remove(userModel);
            }
            
            await _context.SaveChangesAsync();
            TempData["DeleteMsg"] = string.Format("Uzivatel {0} bol uspesne vymazany!", userModel.ToString());
            return RedirectToAction(nameof(Index));
        }

        private bool UserModelExists(int id)
        {
          return _context.UserModel.Any(e => e.Id == id);
        }
    }
}

AspPoistenieBK02/AspPoistenieBK02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="BorisKo" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    
    <!--
    <link rel="shortcut icon" href="~/images/ikona.ico" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/lightbox2/css/lightbox.min.css" asp-append-version="true" />
    -->
</head>

<body>
    <header class="navbar navbar-expand-md navbar-dark bg-dark">
        <nav class="container-fluid">
            <a class="navbar-brand flex-column justify-content-between" asp-controller="Home" asp-action="Index">
                <!-- obrazok je zatial len placeholder-->
                <img src="~/pics/Imperial_small.png" class="d-inline-block align-content-center rounded-circle bg-white" width="64" height="64" alt="logo firmy" />
                Prvá Imperiálna       
            </a>
            <!-- toto je collapse pre velmi uzky styl obrazovky-->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#obsah-navigacnej-listy">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!--navigacka-->
            <div class="collapse navbar-collapse justify-content-between" id="obsah-navigacnej-listy">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">@StringCommon.sc001_Home</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Insurance">@StringCommon.sc002_Insurance</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Contact">@StringCommon.sc003_Contact</a></li>
                    <partial name="_LoggedNavbar" />
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>

    <article>
        <!--
        <div id="centrovac"
        @if (Context.Request.RouteValues.Values.Any(p => p is "Home") && Context.Request.RouteValues.Values.Any(p => p is "Index"))
        {
            <text>class="domu-article"</text>
        }> -->
        <div>
            
            <header>
                <!--<h1>@ViewData["Title"]</h1>-->
                <h1></h1>
            </header>
            

            @RenderBody()

            <!--
            <div class="cistic"></div>
            -->
        </div>
    </article>

    <footer>
        <div class="row bg-dark text-white fixed-bottom">
            <small class="text-center m-3">May the force be with you &copy;BorisKo @DateTime.Now.Year</small>
            <!--
            <a href="https://itnetwork.cz">itnetwork.cz</a>
            -->
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/lightbox2/js/lightbox.min.js" asp-append-version="true"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            $('.alert').alert()
        })
    </script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AspPoistenieBK02/AspPoistenieBK02/Views/Shared/_LoggedNavbar.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        @if (true) //User is admin, nezabudnut no nastavenie role
        {
            <li class="nav-item"><a class="nav-link" asp-controller="UserModels" asp-action="Index">@StringCommon.sc015_NavbarClients</a></li>
            <li class="nav-item"><a class="nav-link" asp-controller="InsuranceModels" asp-action="Index">@StringCommon.sc016_NavbarInsurances</a></li>
        }
        else //common user
        {
            //musi zobrazovat len klientov ucet
            <li class="nav-item"><a class="nav-link" asp-controller="UserModels" asp-action="Index">MojePoistenie</a></li>
        }
    }
</ul>